### ISSUE TITLE
can we figure out a Jenkins Listener to be notified when a Stage changes status (complete/fail)?

### ISSUE THREAD

**Issue by jstrachan** [openshift/jenkins-sync-plugin#13]
tried BuildStepListener so far with no luck. This would avoid all polling and provide more real time updates which would be nice

**Comment by jstrachan** [comment]
I've raised this issue to see if there's an official way to do this in jenkins : https://issues.jenkins-ci.org/browse/JENKINS-33918

**Comment by gabemontero** [comment]
org.jenkinsci.plugins.workflow.flow.FlowExecutionListener arrived in April/May 2017 to workflow-api and the pipeline suite, but that still is not the granularity being talked about here ... that would seem to be a "FlowNodeListener", which does not yet seem to exist.

given this space still seems to be rapidly evolving, my opinion - I'm good for the time being holding on to this issue (though certainly we've been managing with the polling mechanism so far).

@bparees fyi

**Comment by gabemontero** [comment]
OK, with another round of exploring, I've pieced something plausible together that allows us to get notified when a stage either completes/fails:
- the interface that BuildSyncRunListener would have to implement is `org.jenkinsci.plugins.workflow.flow.GraphListener.Synchronous` ... you get notified in real time vs. batched (so there may be performance considerations here)
- the FlowNode impls of note are `org.jenkinsci.plugins.workflow.cps.nodes.StepEndNode` and `org.jenkinsci.plugins.workflow.cps.nodes.StepStartNode`
- The following code snippet printed stage completion status in real time while the job was running:

```
    @Override
    public void onNewHead(FlowNode node) {
        if (node instanceof StepEndNode) {
            StepEndNode sen = (StepEndNode)node;
            String status = "completed";
            if (sen.getExecution().getCauseOfFailure() != null) {
                status = "failed with " + sen.getExecution().getCauseOfFailure().getMessage();
            }
            if (sen.getStartNode().getStepName().equalsIgnoreCase("Stage")) {
                logger.info("GGM stage '" + sen.getStartNode().getDisplayName() + "' has " + status);
            }
            
        }
        
    }
```

Of course the motivation here is that rather than polling runs at an arbitrary intervals, we could work off push events (but perhaps still batch build updates to master given prior results / as needed).

@bparees - you interested in creating a card for further investigating such rework ?

**Comment by bparees** [comment]
> @bparees - you interested in creating a card for further investigating such rework ?

sure, but it definitely won't be very high priority unless the polling approach is shown to have scalability problems.

**Comment by gabemontero** [comment]
Card https://trello.com/c/a3Ox5pwd/1392-pipelineintegration-replace-run-polling-with-a-listener-approach-for-determining-stage-completion opened for devexp tracking.

Of course, if the seed I planted in https://github.com/openshift/jenkins-sync-plugin/issues/13#issuecomment-335269044 triggers the fabric8 team into action, we'll work any PRs they submit.

**Comment by gabemontero** [comment]
closing per process
