### ISSUE TITLE
sync OpenShift Secrets to Jenkins Credentials

### ISSUE THREAD

**Issue by jstrachan** [openshift/jenkins-sync-plugin#131]
right now the sync plugin syncs `Source Secrets` inside `BuildConfigs` to Jenkins `Credentials` which is great; but it would be nice to support other Secrets too. Such as git credentials when using github organisation folder plugin.

So lets also add a watcher of `Secrets` with label `jenkins = sync` and all secrets in the sync namespace should create/update a suitable Credential in Jenkins.

PR on its way soon...

**Comment by jstrachan** [comment]
there's a branch with this fix here https://github.com/fabric8io/jenkins-sync-plugin/tree/job-to-bc

we need to do a bit of rebasing before we can push these changes; will try get to that by mid-May...

**Comment by bparees** [comment]
@csrwng does this overlap w/ what you were trying to do w/ your controller?

**Comment by csrwng** [comment]
It does overlap... you can see my simple python-based controller here: https://github.com/openshift/release/tree/master/jenkins/controllers/secrets
However, it's not intended to be part of the product.

**Comment by bparees** [comment]
per our discussion yesterday, we were thinking about doing this in the jenkins image itself rather than via the sync plugin (thus keeping the sync plugin purely focused on buildconfig/pipeline execution).  But admittedly we hadn't sorted out exactly *how* we were going to do that (something watching the jenkins filesystem for mounted secrets (and updates to those secrets) and injecting it into the jenkins config, basically).

**Comment by bparees** [comment]
@oatmealraisin /cc

**Comment by bparees** [comment]
we're tracking this in trello now:
https://trello.com/c/SGvNKyMM
