### ISSUE TITLE
Enable "Always Pull Image" For Jenkins Slaves

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins-sync-plugin#186]
When the image stream watcher configures the kubernetes plugin, it should enable the "always pull image" feature. Without this flag checked, it is possible that a node will use an old version of the jenkins slave when performing a build.

Screenshot of the slave without the feature enabled.

![screenshot from 2017-11-30 11-50-59](https://user-images.githubusercontent.com/1335137/33443118-02ebec7a-d5b4-11e7-8b05-892299747aab.png)

**Comment by arnaud-deprez** [comment]
You can do this with this option https://github.com/arnaud-deprez/jenkins-docker-openshift/blob/feed1443ef28167b251abf8240a1a603e384397a/slave-gradle/openshift/slave-config-persistent.yml#L50 in your ConfigMap

**Comment by sherl0cks** [comment]
@arnaud-deprez thank you for the info. while that is useful, it is a lot more detail/work than the average user should have to know/do. @gabemontero I'd be keen for your input here when you have a moment.

**Comment by gabemontero** [comment]
@sherl0cks @arnaud-deprez there is actually a lot of activity wrt slave configuration as I type, mostly being driven by @bparees and @jim-minter at the moment.

In fact, @bparees has https://github.com/openshift/jenkins/pull/431/files cooking which is going to enable everyone's slave configs to "always pull", as well as updating the tags off of latest (we recently endured significant upheaval with the 3.7 GA because of customer using the latest tag with the slave images).

With that, I believe updating sync plugin's image stream watch to enable the always pull bit falls in line with all this.  And to your point @sherl0cks , it would be done under the covers and the average user would not have to worry about it.

But in saying that, the change needs to roll up with the work @bparees and @jim-minter are driving.  So I need to confer with / hear from them before committing to anything.

**Comment by sherl0cks** [comment]
@gabemontero all too familiar with those challenges =) I do agree this proposal is in line with the other changes and your plan of attack sounds good to me.

**Comment by bparees** [comment]
i'm fine w/ making the sync plugin set the slave to always pull when it is manufacturing new slave configurations.
