### ISSUE TITLE
Openshift Jenkins Sync listens to multiple Openshift cluster

### ISSUE THREAD

**Issue by jimmychu0807** [openshift/jenkins-sync-plugin#206]
Hi,

We have two openshift clusters deployed, one is UAT, and another PROD. Currently the plugin could only configured to listen to one cluster.

1) Is there a way to listen to more than one openshift cluster **RIGHT NOW**, via API / cmdline? This is for completing my client deployment project in coming week.

2) Would you consider adding corresponding UI to support listening to more than one openshift cluster?

Thank you.

**Comment by bparees** [comment]
1) no
2) we'd consider it but it would be a significant feature to implement.  it's not just configuring the plugin to sync against multiple clusters (which in itself means watching resources in multiple clusters instead of just one) but also tracking in jenkins which cluster a resource came from so data is properly synced to the right place in both directions.

**Comment by jimmychu0807** [comment]
@bparees  Thanks for explaining. I guess there isn't much I can do now (except contributing to the codebase, of course).
