### ISSUE TITLE
Avoid config update if partial config matches?

### ISSUE THREAD

**Issue by alanbchristie** [openshift/jenkins-sync-plugin#245]
I've raised this issue on the advice of Gabe Montero during an email conversation about the occasional loss of agent configuration in OpenShift Origin's Jenmins service (v2.89.4). From the email conversation...

> I’m annotating the ImageStream, essentially doing this: `slave-label: buildah-slave`. The Dockerfile and ImageStream YAML template for my agent (a buildah/skopeo agent) based on jenkins-slave-maven-centos can be found at our public repo (https://github.com/InformaticsMatters/openshift-jenkins-buildah-slave).
> 
> I can understand the agent being replaced when the external image changes but I was curious about why it might change (for no apparent reason).

Gabe's response was...

> Just remembered, our background polling mechanism is most likely updating it.  It gets back to not being able to merge our partial config with any changes you've made on the Jenkins side.  That said, we could try to avoid the update if our partial config matches.

**Comment by gabemontero** [comment]
@alanbchristie - I dove into this in more detail, and as it turns out, the background poll already has some checks in place so that it does not update an existing pod template... memory is not as good as it used to be :-).  

Those checks should be in the version of the plugin that shipped with 3.9.

Just ran a test here and confirmed that behavior, that the background poll does not update the existing tag, where my IST def mimcs yours ...

...expect in one respect ... I don't have the scheduled import policy bit set on ...i.e. https://github.com/InformaticsMatters/openshift-jenkins-buildah-slave/blob/master/slave.yaml#L75-L76

That is what is going on ... the scheduled import modifies the images stream regardless (the version bit for example, and the last modified time), even if the source docker image is the same, and our main event processing path is seeing that and updating the template.

Of course we are assuming there wasn't an actual image change you were unaware of that the scheduled import picked up on.

But yeah, our event processing path assumes if the IS is modified, just go with it.

So a slight variant, but assuming the code change doesn't get messy (I don't think it shoud, but we'll see), I'll still add the comparison of the docker ref, and just make the usage common to both paths.

**Comment by alanbchristie** [comment]
OK, and I’m not aware of any docker changes in the background.

----
Alan
