### ISSUE TITLE
Building Jenkins workflow job synced from remote project causes remote project to redundantly trigger pipeline

### ISSUE THREAD

**Issue by andyfeller** [openshift/jenkins-sync-plugin#251]
There appears to be an edge case regarding [BuildDecisionHandler](https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java) and building Jenkins workflow job synced from a remote OpenShift namespace.  When BuildDecisionHandler reaches into the OpenShift namespace the Jenkins workflow job was synced from and triggers the OpenShift JenkinsPipelineStrategy BuildConfig, this will cause a Jenkins instance within the OpenShift namespace to also run it's synced copy of Jenkins workflow job.  In some cases like a deployment pipeline, this can cause multiple deployments to stomp on one another.

**Comment by gabemontero** [comment]
Hey @andyfeller 

Can we draw this scenario out with some more precise naming, make sure I understand.

1) you have (at least) 2 namespaces, let's call them `projA`, `projB`, etc.

2) you have a a pipeline BC called `foo` ... is it defined in just one of the projects, or in both `projA`,  `projB`, etc. ?

3) you have a jenkins instance running in `projA`, `projB`, both, or another namespace, let's call it `projC`  ? .... based on the answers, let's call them `jenkinsA`, `jenkinsB`, `jenkinsC`, etc.

Or do you also have a jenkins running outside of openshift in addition to jenkins running within an OpenShift Pod? ... if so, let's call that `jenkinsXternal`

4)  Which jenkins instance(s) are monitoring which namespaces ?

**Comment by andyfeller** [comment]
Hey Gabe,

Thanks for the follow up!  I’ve outlined the scenario visually on Jenkins User topic (https://09023362727002364442.googlegroups.com/attach/6dbd789bece5d/openshift-sync%201.0.24%20BuildDecisionHandler%20race%20condition.png?part=0.1&vt=ANaJVrGvdtI6W0FrUPorBw8YMkEdL24nxAsDzOZTfnJDxfOMeZpJUvlaQVirC2iWUYol0FBlKD0aJoCSm27AptSixVIsgtV-inJuR5pY7AboClb5Sk_P_KI) but let me do a better job explaining here.

2 OpenShift projects (projA, projB) each with Jenkins services using OpenShift Sync plugin.

projA has a JenkinsPipelineStrategy BuildConfig (bcA), which has been synced to its Jenkins (jenkinsA) as a workflow job (jobA).

jenkinsB has been configured to sync with projA thus has a workflow job (jobB) but no BuildConfig itself.

If jobB is scheduled from within jenkinsB, jenkinsB will reach into projA and trigger bcA, thus scheduling jobA.  I believe this is due to the BuildDecisionHandler trying to reflect the workflow job being scheduled with the BuildConfig.

**Comment by gabemontero** [comment]
Thanks @andyfeller that cleared things up.

First, given your config, which results in two separate sync plugin instances monitoring a given BC, then yes, the code as currently designed will result in instantiating a build for the given BC in its namespace.  So yes that will result in the which ever sync plugins instances are listening to that namespace starting jobs in the jenkins instances they are located in.

Safe to say, having multiple jenkins/syncplugin instances each monitoring a single project/namespace is not a scenario that was envisioned as something to support.  And this is the first instance of somebody reporting such an attempt.

So we can look at this from two perspectives:

1) Was this set up intentional?  If so, can you elaborate what motivated it (I have a guess or two in mind, but would like to hear any uncorrupted view from you) ?

2) Should multiple sync plugins running in an OpenShift cluster coordinate to prevent possible inadvertent misconfiguration from users? .... ultimately, that will be a cost/benefit prioritization analysis on our end ... I'll initially characterize the cost as "needing sophistication"

@bparees @sspeiche ^^

**Comment by bparees** [comment]
@gabemontero agree w/ everything you say, though it also ought to be possible for the sync plugin to annotate the build object it creates in such a way as to prevent other sync plugins from seeing it and thinking they need to act on it (the other sync plugins can check if the annotation exists and if so, they would not start a jenkins job run).  (Does the sync plugin create the build object directly, or does it create a buildrequest object? It's particularly trivial if it's the former, possibly harder if it's the latter).

None of that will help, of course, if the user creates the build object in openshift.  At that point there's no clear sync plugin instance that can "own" it, and you're going to get multiple job runs kicked off.

**Comment by gabemontero** [comment]
On Mon, Aug 13, 2018 at 5:04 PM, Ben Parees <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> agree w/ everything you
> say, though it also ought to be possible for the sync plugin to annotate
> the build object it creates in such a way as to prevent other sync plugins
> from seeing it and thinking they need to act on it (the other sync plugins
> can check if the annotation exists and if so, they would not start a
> jenkins job run). (Does the sync plugin create the build object directly,
> or does it create a buildrequest object? It's particularly trivial if it's
> the former, possibly harder if it's the latter).
>

It instantiates the latter ... a BuildRequest, and yep, you are starting to
get at the "non-trivia" nature of this.

And even with instantiating a Build object ... you get permutations around
allowing parallel vs. serial builds ... we can't necessarily assume serial
... checking for jenkins runs in queue vs. actually running  ... there are
nuances
outside the core OpenShift API object creation to consider.

**Comment by andyfeller** [comment]
@gabemontero I came across this situation in migrating from one-off Jenkins instances to a consolidated Jenkins instance that synced JenkinsPipelineStrategy BuildConfigs as [documented within the openshift-sync plugin](https://github.com/openshift/jenkins-sync-plugin#other-configuration).  I admit this is currently a problem as long as Jenkins auto provisioning is enabled, however I'm still working to get this disabled as it currently can only be done cluster wide.

Ideally, I think it's probably better to provide some configuration option within buildconfig.spec.strategy.JenkinsPipelineStrategy on whether BuildDecisionHandler should trigger the source BuildConfig when Jenkins workflow is scheduled.

At the least, it would be good to update documentation to highlight this case.

Thoughts?

**Comment by bparees** [comment]
> Ideally, I think it's probably better to provide some configuration option within buildconfig.spec.strategy.JenkinsPipelineStrategy on whether BuildDecisionHandler should trigger the source BuildConfig when Jenkins workflow is scheduled.

I'm struggling to follow the behavior you're looking for with this.  You've got 2 jenkins instances, both w/ sync plugins monitoring the same namespace.

1) If you start a workflow in jenkins, the build gets created and the other jenkins sees it and creates a 2nd workflow (the problem you are currently facing)

2) If you start a build in openshift, both jenkins will see it and start their respective workflows.

If it were possible to prevent the creation of builds when the workflow starts, that would help you with (1), but it would also mean there would be no build object to sync the workflow progress/state to.  And it would not help (2).


> I admit this is currently a problem as long as Jenkins auto provisioning is enabled, however I'm still working to get this disabled as it currently can only be done cluster wide.

yeah as @gabemontero found when he dug into this recently, we had an RFE for this that we abandoned, but perhaps we need to revisit it.

**Comment by andyfeller** [comment]
Oh I’m not advocating on multiple Jenkins monitoring the same BuildConfigs; merely postulating one way to prevent one from being triggered.

End of the day, I’d most be happy with disabling auto provisioning for select projects and updating existing documentation of openshift-sync monitoring multiple namespaces to avoid this situation.

**Comment by gabemontero** [comment]
OK thanks for the clarification @andyfeller 

So, I'll chime in now on what I hinted at with https://github.com/openshift/jenkins-sync-plugin/issues/251#issuecomment-412662017 about where my head went this ....

... what if the user tried this with redundancy or single point of failure in mind ... they were concerned for whatever reason that a Jenkins instance could stay "unhealthy" in a given project (perhaps because of other constraints ??)

A bit of a stretch for sure (which is why I did not want to lead with it)

Anyway, if we wanted to take on such a scenario, I would not think we would have separate instances coordinate at the build or build request object level.  Probably employ a primary  / backup approach using a separate api object to coordinate.

But disabling auto provisioning for select projects is probably the more straight line path.

So yeah, things for us to dive into longer term, with documenting a warning in the short term as @bparees alluded to.

**Comment by gabemontero** [comment]
Also, there is a workaround @andyfeller  .... the autoprovisioning code looks for a service named "jenkins" after the on/off config check .... if such a service exists, it will not provision another jenkins instance.

You could create a dummy service in the namespaces you do NOT want jenkins running in.

**Comment by andyfeller** [comment]
Thanks for that reminder Gabe but I must admit that “feels bad” and only a last resort if disabling auto provisioning cluster wide runs into a hitch.

**Comment by gabemontero** [comment]
Opened the above doc related PRs to add the warning.

The request for per project control of auto provisioning is re-registered.

Per process, closing this out.

**Comment by gabemontero** [comment]
thanks for the feedback @andyfeller
