### ISSUE TITLE
Support using secrets managed in Jenkins namespace for pipelines synced from remote namespaces

### ISSUE THREAD

**Issue by andyfeller** [openshift/jenkins-sync-plugin#253]
With openshift-sync plugin capability to sync JenkinsPipelineStrategy BuildConfig from remote namespaces, we were wondering if it'd be possible and preferable to centrally manage the source secret within the Jenkins namespace.  Currently, only the secrets tied to the BuildConfig are configured for the resulting Jenkins workflow jobs.  This would make overall management easier and keep unnecessary credentials out of the hands of some.

**Comment by gabemontero** [comment]
Hey @andyfeller 

Do you know about our secret to credential mapping feature?  Based on you description it seems like it would fit your needs.

See https://github.com/openshift/jenkins-sync-plugin/#openshift-jenkins-sync-plugin and https://docs.okd.io/latest/using_images/other_images/jenkins.html#sync-plug-in for details.

Certainly feel free to post any follow up questions here, and we can reopen if some nuance to your requirement emerges in any subsequent discussion that results in a possible feature request.

thanks

**Comment by andyfeller** [comment]
Hey @gabemontero!

AFAIK openshift-sync plugin will only wire in the source secret declared in the BuildConfig when synchronizing and building the workflow job.  The problem is that every namespace how has source secrets when only Jenkins might need them, which I can make work.  Rather I was thinking there would be a way for openshift-sync to allow a Secret synced from Jenkins namespace to be used instead

**Comment by andyfeller** [comment]
I was thinking maybe [CredentialsUtils.updateSourceCredentials](https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java#L59) could be updated to fall back to a Jenkins credential configured within the GlobalPluginConfiguration if the BuildConfig's Secret couldn't be found.

**Comment by gabemontero** [comment]
Hey @andyfeller 

Yes, as part of job configuring, sync plugin will take the BC source secret and upsert a jenkins credential.

But you can sync *any* openshift secret (whether it is connected to the BC or not) and *any* time (i.e. even prior to triggering a job) to a jenkins credential.

Then just leverage whatever credential you want during you git operations, etc. during you job run's builds.

I'm not seeing why that can't suite your needs.  If it cannot, can you elaborate why?

Also, the GlobalPluginConfiguration credential is meant for accessing openshift itself, not for accessing any source repo's associated with your build config (which is what the build config secret is intended for).

**Comment by andyfeller** [comment]
The problem is that _only the BC source secret_ is wired into the Jenkins workflow job definition whereas I wanted some other secret synced with Jenkins used as an option so I could isolate the various places I have to manage it.

CredentialsUtils.getSourceCredentials
```
    public static synchronized Secret getSourceCredentials(
            BuildConfig buildConfig) {
        if (buildConfig.getSpec() != null
                && buildConfig.getSpec().getSource() != null
                && buildConfig.getSpec().getSource().getSourceSecret() != null
                && !buildConfig.getSpec().getSource().getSourceSecret()
                        .getName().isEmpty()) {
            Secret sourceSecret = getAuthenticatedOpenShiftClient()
                    .secrets()
                    .inNamespace(buildConfig.getMetadata().getNamespace())
                    .withName(
                            buildConfig.getSpec().getSource().getSourceSecret()
                                    .getName()).get();
            return sourceSecret;
        } else if (getSourceSecretFromPluginConfigurationAlreadyInJenkins) {
                 // Go use that
        }
        return null;
}
```

**Comment by gabemontero** [comment]
Ah, I remember now.  You are referring to the GitSCM object that can be included in the job's flow def.  Sort of the "built-in" SCM, where we happen to also perform secret to credential mapping for you as part of that.... the code is actually BuildConfigToJobMapper (but that code ultimately calls methods which call the getSourceCredentials method you mentioned above.

But yeah you get access to the Jenkinsfile in the scm repo via that cred.

I was thinking about the fact that you can pass a credentials ID into the git plugin's pipeline various DSL.  That is where I would expect a "centralized" pattern to manifest, with explicit use of that DSL.

I don't think which namespace jenkins is in vs. which namespace the bc is in (you mentioned "remote" bc's up top) matters.

Otherwise, yeah, we generally like to keep as much consistency between the jenkins/openshift artifacts (job/bc, job run/build), and today "source secrets" and "build configs" are in the same namespace.  

It just so happens that Jenkins scopes credentials by default globally (though you can override and create a specific domain ... don't remember if you can control who can access that domain though), but that is different than what openshift does with secrets.

Coupling the source secret and bc, as is done currently in openshift (for all the build strategies, not just pipeline), and translating that to the jobs gitscm, still feels right to me, vs. some arbitrary secret from another namespace.  I could maybe see allowing for more control on which jenkins domain the credential gets stored in (vs. the global one), if we think that helps to "keep unnecessary credentials out of the hands of some." as you noted in the description.

Thoughts?

@bparees fyi

**Comment by bparees** [comment]
What options does a user have today if they want to provide the GitSCM credential manually (ie not let openshift-sync automatically use the one from the buildconfig?)

I could maybe see an argument for allowing someone in jenkins to set that to an existing jenkins credential explicilty, if that's not possible today (at which point the ability of the sync plugin to sync secrets into jenkins credentials, coupled w/ the user choosing that jenkins credential for their Job's GitSCM access, would be sufficient if not ideal in terms of manual steps required).

I'm wary of going the step further for, i think the same reasons @gabemontero outlined which is that the mapping between jenkins objects and openshift objects starts to breakdown and the mechanism for configuring what secret(from where) to use(where) starts to get pretty messy.

**Comment by andyfeller** [comment]
Thanks for chiming in @bparess and for baring with me @gabemontero _(much appreciated)_!

So I think people already get confused in general talking about the nuances of OS Secrets being synced to Jenkins as credentials including some who are syncing Secrets from multiple projects.  On top of that, some are syncing Secrets from the namespace housing Jenkins and making them available to others leading to more confusion without this. 

$0.02: this won’t be the thing to make it worse and has potential to make it easier in some regards.  Wish we had more people using multi project sync to talk with.

**Comment by gabemontero** [comment]
Responses to various items over the weekend:

1) @bparees - the user can change the GitSCM creds used for checkout during builds/runs from the jenkins console, editing their jobs' config.  Of course, if the correct creds are not referenced by the BC, until the correct creds are provided, any attempts to start a build/run would fail.

But it could be a tactical stop gap to a more elegant solution (where I propose a more elegant solution below).

2) I revisited the Jenkins Global Security and Jenkins Domains a bit to refresh my memory.  The pertinent particluars:
  a) A domain can be provided a specification that ultimately controls whether the list of credentials in the domain can be displayed for the currently logged in user in the various config panel drop downs in Jenkins 
  b) The current list of pretty basic, though there is a docker server and maven options currently provided ... we do not currently provide one along OpenShift lines, but presumably could
  c) Via global jenkins security, you can control who can view, manage credentials and domains ... though I see no way to control who can look at which domains
  d) With the current set of permissions we set up with the OpenShift Login plugin, anybody with view access to the Jenkins project can view credentials, anybody with admin access can manage everything
  **e) With things as they stand today, there is certainly no scoping of jenkins credentials to a jenkins folder today, which would be the equivalent of what openshift does by scoping secrets to a namespace (where any Pipeline BC, or Jenkins Job effectively, can access secrets within its namespace**

3) To reiterate an early comment by me, defaulting the credential used for git scm checkout to the jenkins SA, which is what @andyfeller 's suggestion at https://github.com/openshift/jenkins-sync-plugin/issues/253#issuecomment-415725478 means, would not work here.

4) That said, I think @andyfeller is correct in that the openshift secret / jenkins credential integration is not entirely seamless (see point 2)d) and 2)e) above)

But I think I do see a path to make it better, except for perhaps 2c)  (pending prioritization of the work of course):

- we already have a requirement to make the login plugin's permission mapping configurable , and in looking at the code, I do see permissions for "using" credentials vs. "viewing" them ... perhaps after some testing from upstream users like @andyfeller , where they could configure the permission mappings, we could change the default to "using" vs. "viewing", and avoid some the the people seeing various credentials they perhaps should not see ... I interpreted some of @andyfeller 's comments as referring to such situations

- perhaps sync plugin could implement a DomainSpecification that limits the credentials provided in gui listings on a jenkins folder basis, where we then perform self SARs against the namespace mapping to the folder, to see if the authenticated user can look at the secrets, and hence look at the credential

this way, we better map the organization and constraints what openshfit does ... hopefully reducing confusion on the mapping, better limiting who views what, etc.

and finally, on the job creation piece, sync plugin, rather than adding the credential to the global domain, creates a domain with the appropriate filtering specification, and adds the credential there.

Thoughts?

**Comment by andyfeller** [comment]
If I understand you correctly @gabemontero, you’re pointing out an issue where the Jenkins credentials created by openshift-sync plugin are too open vs the intent behind OpenShift secrets.  I certainly applaud shoring that area up though don’t know how restricting access by folder will work gene someone disabled folders.  If so, these would be good changes to makes.

That said, could you help me understand how this addresses the original request?

**Comment by gabemontero** [comment]
Hey @andyfeller 

- What I described in https://github.com/openshift/jenkins-sync-plugin/issues/253#issuecomment-416294380 addresses the last part of your description, namely `keep unnecessary credentials out of the hands of some.`  Assuming I am on the same page with your intent with those words.  Hopefully I provided enough detail so you can discern whether you agree that I'm addressing your point there.

- As far the notion of `centrally manag[ing] the source secret`, per the comments from both @bparees and myself, we are not in agreement that should be a path we pursue.

**Comment by andyfeller** [comment]
Fair enough!  Just making sure I understand 🙂 So I’d expect you’d create a Trello card for whatever changes mentioned above you see fit.  Thanks again guys!

**Comment by gabemontero** [comment]
We have been forced to migrate from trello to jira @andyfeller (and the public jira is in progress, but not ready yet).

But I have created DEVEXP-158 in this still private Jira to track.
