### ISSUE TITLE
OpenShift and Jenkins seem out of sync for build status

### ISSUE THREAD

**Issue by dharmit** [openshift/jenkins-sync-plugin#265]
We're seeing number of builds for which Jenkins interface shows that builds are over. But when we look at `oc get builds` output, these builds show running. 

Here's example output:
```bash
$ oc get builds | grep Running
centos-mongodb-34-centos7-latest-2                              JenkinsPipeline   Git@master                                      Running    2 hours ago         
centos-nginx-110-centos7-latest-3                               JenkinsPipeline   Git@master                                      Running    2 hours ago         
centos-nginx-18-centos7-latest-3                                JenkinsPipeline   Git@master                                      Running    2 hours ago         
centos-nodejs-4-centos7-latest-6                                JenkinsPipeline   Git@master                                      Running    About an hour ago   
centos-nodejs-8-centos7-latest-2                                JenkinsPipeline   Git@master                                      Running    2 hours ago         
```

Here's the screenshot from Jenkins dashboard saying that build has already finished successfully. In fact all the builds in above output have actually finished on Jenkins. But they're showing as `Running` in `oc` output.

![screenshot from 2018-10-05 14-49-30](https://user-images.githubusercontent.com/713521/46527321-7eae0a80-c8ae-11e8-8c6e-d2aa26472104.png)

**Comment by gabemontero** [comment]
hey @dharmit 

Just tried a few or our sample pipelines with v1.0.29 of the sync plugin (our latest version as of this writing) and am not seeing this issue.

So to try to distinguish between what I am seeing and what you are seeing, please provide:
- the version of the openshift cluster being used
- the version of the sync plugin being used 
- tag/version of the openshift jenkins image, if you are using that
- the jenkins server logs (the jenkins pod logs if your are running our openshift jenkins image in a pod, otherwise the jenkins server logs from whatever standalone jenkins server you have that is running the sync plugin .... and if running jenkins outside of a openshift pod, please provide the version of jenkins you are using)

thanks

**Comment by valdestrijus** [comment]
Hello, I am getting the same, but it is not replicated each time I run pipeline, it happens from time to time. Can not get pattern.

Jenkins image version: registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.9.30
Jenkins version: Jenkins ver. 2.89.4
Openshift cluster version: 
OpenShift Master:
v3.7.64
Kubernetes Master:
v1.7.6+a08f5eeb62

Openshift-sync plugin version: 1.0.24
OpenShift Client Jenkins Plugin: 1.0.14
OpenShift Login Plugin: 1.0.5
OpenShift Pipeline Jenkins Plugin: 1.0.54

The original jenkins image has 1.0.7 plugin versions but we updated plugins manually as we need resource-locking fixes.

Also I think there might be some synchronization issues because of 3.7 oc cluster.

Logs:
```shell
Oct 09, 2018 6:02:20 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@66b92b87[myproject-code-dev/myproject-code-dev-myproject-frontend-pipeline] runs for BuildConfig myproject-code-dev/myproject-frontend-pipeline
Oct 09, 2018 6:02:20 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@554454ac[myproject-code-dev/myproject-code-dev-myproject-infra-test-pipeline] runs for BuildConfig myproject-code-dev/myproject-infra-test-pipeline
Oct 09, 2018 6:02:20 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@2a88e86c[myproject-code-dev/myproject-code-dev-myproject-workers-pipeline] runs for BuildConfig myproject-code-dev/myproject-workers-pipeline
Oct 09, 2018 6:07:19 AM io.fabric8.jenkins.openshiftsync.CredentialsUtils upsertCredential
INFO: Updated credential myproject-code-dev-myproject-automation-sshkey from Secret NamespaceName{myproject-code-dev:myproject-automation-sshkey} with revision: 265118150
Oct 09, 2018 6:07:19 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Reconciling job runs and builds
Oct 09, 2018 6:07:19 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@df7e971[myproject-code-dev/myproject-code-dev-myproject-backend-pipeline] runs for BuildConfig myproject-code-dev/myproject-backend-pipeline
Oct 09, 2018 6:07:19 AM io.fabric8.jenkins.openshiftsync.CredentialsUtils upsertCredential
INFO: Updated credential myproject-code-dev-myproject-automation-sshkey from Secret NamespaceName{myproject-code-dev:myproject-automation-sshkey} with revision: 265118150
Oct 09, 2018 6:07:19 AM io.fabric8.jenkins.openshiftsync.CredentialsUtils upsertCredential
INFO: Updated credential myproject-code-dev-db0921p from Secret NamespaceName{myproject-code-dev:db0921p} with revision: 265118149
Oct 09, 2018 6:07:19 AM io.fabric8.jenkins.openshiftsync.CredentialsUtils upsertCredential
INFO: Updated credential myproject-code-dev-myproject-automation-sshkey from Secret NamespaceName{myproject-code-dev:myproject-automation-sshkey} with revision: 265118150
Oct 09, 2018 6:07:19 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@f565531[myproject-code-dev/myproject-code-dev-myproject-devbox-pipeline] runs for BuildConfig myproject-code-dev/myproject-devbox-pipeline
Oct 09, 2018 6:07:19 AM io.fabric8.jenkins.openshiftsync.CredentialsUtils upsertCredential
INFO: Updated credential myproject-code-dev-myproject-automation-sshkey from Secret NamespaceName{myproject-code-dev:myproject-automation-sshkey} with revision: 265118150
Oct 09, 2018 6:07:20 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@66b92b87[myproject-code-dev/myproject-code-dev-myproject-frontend-pipeline] runs for BuildConfig myproject-code-dev/myproject-frontend-pipeline
Oct 09, 2018 6:07:20 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@554454ac[myproject-code-dev/myproject-code-dev-myproject-infra-test-pipeline] runs for BuildConfig myproject-code-dev/myproject-infra-test-pipeline
Oct 09, 2018 6:07:20 AM io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds
INFO: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@2a88e86c[myproject-code-dev/myproject-code-dev-myproject-workers-pipeline] runs for BuildConfig myproject-code-dev/myproject-workers-pipeline

```
Also worth to mention that at the same time we were running `myproject-workers-pipeline` and `myproject-backend-pipeline` and one completed and the other `myproject-workers-pipeline` not. It looks like the error happens somewhere in the plugin and it is not propagated, because from logs it does not show that it is errored.

**Comment by gabemontero** [comment]
OK @valdestrijus @dharmit 

Since it is intermittent, this will get trickier.

Thoughts on the latest:
- get me the yaml for the openshift builds corresponding to the pipeline job runs the next time this occurs ... the presence or lack of presence of certain data could provide clues to us
- Nothing from the logs provided by either @valdestrijus or @dharmit provide any clues

In the future, if you could either provide the entire jenkins log, or at least enough of the log where the start of the build is recorded, perhaps I'll catch something of relevance

- otherwise, catching a failure with trace turned on could help helpful ... here is a screen shot of the classes to turn trace on for:

![sync-plugin-trace](https://user-images.githubusercontent.com/3594868/46691419-e4620580-cbd2-11e8-9c01-944240898904.png)

**Comment by disposab1e** [comment]
Still the same hier...

**Comment by gabemontero** [comment]
it is possible that the https://github.com/openshift/jenkins-sync-plugin/commit/1d2f5aa169bcfae26aaea456f9f8795e640586c8 fix that addressed multiple builds getting invoked could also have some bearing wrt synching build status

v1.0.34 has that change

Closing this out then.  Otherwise, a repro with the debug I asked for in https://github.com/openshift/jenkins-sync-plugin/issues/265#issuecomment-428308260 against v1.0.34 is needed.
