### ISSUE TITLE
Not honored: <foldersEnabled>false</foldersEnabled> 

### ISSUE THREAD

**Issue by disposab1e** [openshift/jenkins-sync-plugin#284]
With this configuration in place all Builds still have an folder name in Jenkins.

<foldersEnabled>false</foldersEnabled>

OpenShift 3.11.82
Jenkins: 2.138.4
OpenShift Sync Plugin:  1.0.31

**Comment by gabemontero** [comment]
I was able to reproduce this locally ... investigating

**Comment by gabemontero** [comment]
Sorry - false alarm.  It is working for me.  I just got confused by the job name.  Which is perhaps what you mean in your description @disposab1e 

So even with folders disabled, the job name will still be `<namesapce>/<build config name>` ... but a jenkins folder will not be created.  It will be a top level job item.

We still include the namespace/project in the name to handle a jenkins instance monitoring multiple namespaces/projects.

I even tested with a folder whose name is the namespace/project already created, and then created a pipeline bc ... it did not place the new job in the folder, but created it as a top level item.

I do not see us changing and of this behavior at this point.

If you are saying it is creating / placing the new job in the folder, since I'm not seeing that, the only course of action would be to get your jenkins logs and/or reproduce with trace.

Reopen if that is what is going on and you want to diagnose accordingly.

**Comment by disposab1e** [comment]
@gabemontero Makes sense! Thanks for clarification on this!
