### ISSUE TITLE
How should I migrate builds to a new OpenShift cluster?

### ISSUE THREAD

**Issue by vfreex** [openshift/jenkins-sync-plugin#312]
We are migrating our pipeline builds to a new OpenShift cluster. I tried copying build directories (/var/lib/jenkins/jobs) of the old Jenkins to the new Jenkins but those builds were deleted by the Sync plugin (because they are not associated with OpenShift build objects). Manually creating OpenShift build objects doesn't work with me, as using oc to create build objects doesn't seem to take effects. What's the best practice to migrate the build history?

**Comment by gabemontero** [comment]
It is not a scenario that has been considered @vfreex 

And as an FYI, your manual attempt of creating builds didn't work because the sync plugin pruning logic compares the build UID saved in the job run against any builds it finds in the monitored namespace.  Your created build objects will have different UIDs so they won't be honored.

I suggest you open an RFE against "OpenShift Container Platform" and the "Images" component.  @openshift/sig-developer-experience will then get that translated to an item on the Jira board (which is not open yet hence the need for the RFE.

Also, note, the entire openshift/jenkins suite is in the process of getting transitioned to the RH devtools team.  Such a feature might not get implemented prior to that transition.

I'll copy those guys as well.

FYI everyone ... @vfreex if I recall correctly is on the RH Upshift team.

@waveywaves @akram @sthaha @siamaksade FYI

**Comment by vfreex** [comment]
@gabemontero Thanks for the information.

**Comment by gabemontero** [comment]
for @akram and @waveywaves - either adding a config option to disable the pruning in build watcher or allowing for a job/run count that is way higher than the ttl's for openshift builds on the openshift side would be the implemenations options here

**Comment by vfreex** [comment]
@gabemontero Sorry for late update on this.  I haven't bring a RFE yet. Is there any progress that you made? If no, I will create it.

**Comment by akram** [comment]
Hi @vfreex 

@waveywaves and I will put this with the subjects we will look at in the next weeks. @waveywaves is currently working on an RFE approaching your request, so we should propose you an implementation then.

/assign @waveywaves

**Comment by vfreex** [comment]
@akram That'll be great! Thanks.
